# -*- coding: utf-8 -*-
"""Single Render bootstrap: final synchronized UI/auth visibility guard."""
import re
import wsgi
import member_auth_fix
import student_gemini
import admin_manager
import ui_sync
from flask import session

app = wsgi.app
_original_wsgi = app.wsgi_app


def _filter_final_response(environ, start_response):
    captured = {}

    def capture_start(status, headers, exc_info=None):
        captured['status'] = status
        captured['headers'] = list(headers)
        captured['exc_info'] = exc_info
        return lambda data: None

    iterable = _original_wsgi(environ, capture_start)
    try:
        body = b''.join(iterable)
    finally:
        if hasattr(iterable, 'close'):
            iterable.close()

    headers = captured.get('headers', [])
    ctype = next((v for k, v in headers if k.lower() == 'content-type'), '')
    if 'text/html' in ctype:
        text = body.decode('utf-8', 'replace')
        path = environ.get('PATH_INFO', '') or '/'
        admin = session.get('role') == 'admin'

        # FINAL BRANDING: this is applied after every UI module has rendered.
        text = text.replace('📚 Ngân hàng câu hỏi GitHub', '📚 Luyện Đề Toán Lý')
        text = text.replace('Ngân hàng câu hỏi GitHub', 'Luyện Đề Toán Lý')
        text = text.replace('MỤC LỤC · GitHub', 'MỤC LỤC')
        text = text.replace('MỤC LỤC • GitHub', 'MỤC LỤC')
        text = re.sub(r'Nguồn đề:\s*bank_index\.json\s*\+\s*ngan-hàng/\\*\.tex\s*·\s*Google Sheet không dùng cho đề',
                      'Zalo thầy Minh 0946111107', text, flags=re.I)

        # GitHub is visible ONLY after a real ADMIN session, never merely
        # because the URL starts with /admin or /github.
        can_show_github = admin and (
            path == '/admin' or path.startswith('/admin/') or
            path == '/github' or path.startswith('/github/')
        ) and not path.startswith('/admin/login')

        if not can_show_github:
            # Remove external and internal GitHub navigation links.
            text = re.sub(
                r'<a\b[^>]*(?:href=["\'][^"\']*github\.com[^"\']*["\']|href=["\']/github(?:/|["\']))[^>]*>.*?</a>',
                '', text, flags=re.I | re.S
            )
            text = re.sub(r'<a\b[^>]*>\s*(?:🐙\s*)?GitHub\s*</a>', '', text, flags=re.I | re.S)
            text = re.sub(r'<button\b[^>]*>\s*(?:🐙\s*)?GitHub\s*</button>', '', text, flags=re.I | re.S)

            # Old catalog headers generated by previous UI modules.
            if path.startswith('/member') or path == '/':
                text = text.replace('MỤC LỤC · GitHub', 'MỤC LỤC')
                text = text.replace('MỤC LỤC • GitHub', 'MỤC LỤC')
                text = text.replace(' · GitHub', '')
                text = text.replace(' • GitHub', '')

        # Responsive final brand styling for laptop/tablet/phone.
        responsive = """
<style>
.zalo-brand{font-size:12px;font-weight:700;margin-left:10px;opacity:.95}
@media(max-width:700px){.topin{padding:8px 10px;align-items:flex-start}.brand{font-size:17px;line-height:1.2;white-space:normal}.sub{font-size:10px}.zalo-brand{display:block;margin:2px 0 0;font-size:11px}.nav{gap:4px}.nav a{padding:6px 8px;font-size:12px}}
</style>
"""
        text = text.replace('</head>', responsive + '</head>', 1)
        body = text.encode('utf-8')
        headers = [(k, v) for k, v in headers if k.lower() != 'content-length']
        headers.append(('Content-Length', str(len(body))))

    start_response(captured.get('status', '200 OK'), headers, captured.get('exc_info'))
    return [body]


app.wsgi_app = _filter_final_response
